### PR TITLE
Allow to dynamically change color

### PR DESCRIPTION
**Pull request by tdassonville**
The color is currently only customizable via the xml, as using setColor() isn't actually changing the Paint...

### CODE REVIEW

**Comment by HugoGresse** [comment]
Thanks! do you have any other issue with the library?

**Comment by tdassonville** [comment]
So far so good ;)
Ideally I should evolve to something actually driven by the music that's playing. But your lib makes for a good trick ;)
I was looking for an easy to integrate animation, to get a sense of what my app will look like, and it is perfect for that! Thanks for sharing 👍

**Comment by HugoGresse** [comment]
FYI: version `1.0.17` has been released last week. 
Thanks for the PR!

**Comment by tdassonville** [comment]
Yes, I have seen that yesterday, already updated the app to this new
release ;)
Thanks for your reactivity!

Le mar. 29 mai 2018 à 09:01, Hugo Gresse <notifications@github.com> a
écrit :

**Pull request merged**
